In [1]:

import numpy as np


In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([(1.5,2,3), (4,5,6)], dtype=float)

In [5]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [6]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype=float) 

In [7]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [8]:
x=np.zeros((3,4))

In [9]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
a = np.ones((2, 3, 4), dtype=np.int16)

In [11]:
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [12]:
b = np.arange(10, 25, 5)

In [13]:
b

array([10, 15, 20])

In [14]:
c = np.linspace(0, 2, 9)

In [15]:
c

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
a = np.full((2, 2), 7)

In [18]:
a

array([[7, 7],
       [7, 7]])

In [19]:
c = np.random.rand(2, 2)

In [20]:
c

array([[0.84507974, 0.88407549],
       [0.9702405 , 0.47370593]])

In [21]:
for name, arr in zip(['a', 'b', 'c'], [a, b, c]):
    print(f"\nArray {name}:")
    print("Shape:", arr.shape)
    print("ndim:", arr.ndim)
    print("Size:", arr.size)


Array a:
Shape: (2, 2)
ndim: 2
Size: 4

Array b:
Shape: (3,)
ndim: 1
Size: 3

Array c:
Shape: (2, 2)
ndim: 2
Size: 4


In [25]:
print(b.dtype)
print(b.dtype.name)


int32
int32


In [26]:
b_int = b.astype(int)
print(b_int)

[10 15 20]


In [28]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)])
print(a + b)

[[2.5 4.  6. ]
 [5.  7.  9. ]]


In [29]:
a-b

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [30]:
b*b

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [31]:
b/b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [33]:
np.sum(b)

np.float64(21.5)

In [34]:
np.min(b)

np.float64(1.5)

In [35]:
np.max(a)

np.int32(3)

In [36]:
np.cumsum(b)

array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5])

In [37]:
np.mean(a)

np.float64(2.0)

In [38]:
np.median(b)

np.float64(3.5)

In [40]:
np.std(a)

np.float64(0.816496580927726)